version: '3.7'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
      MYSQL_DATABASE: cars_dev
    ports:
      - "3307:3306"  # Cambié el puerto externo a 3307 para evitar conflicto con otros servicios
    networks:
      - mi_proyecto_docker_backend_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    environment:
      PMA_HOST: mysql  # Sigue usando "mysql" para que se conecte al servicio mysql
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8081:80"  # Puedes dejar el puerto de phpMyAdmin en 8081
    networks:
      - mi_proyecto_docker_backend_network

networks:
  mi_proyecto_docker_backend_network:
    external: true

